# Configuration for Travis CI

# sudo is required for Docker calls
sudo: required

# mark our language as Python
language: python

# add docker as dependent service
services:
  - docker

# main script
# for the push to work, the variables below must be set
# pushes to Heroku registry, app goes live from there
script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" registry.heroku.com
  - docker build -t registry.heroku.com/sensorsiesta-ubbse2016/web src
  - docker push registry.heroku.com/sensorsiesta-ubbse2016/web
